#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v3
# autospec commit: ab27b0e
#
Name     : spdlog
Version  : 1.13.0
Release  : 14
URL      : https://github.com/gabime/spdlog/archive/v1.13.0/spdlog-1.13.0.tar.gz
Source0  : https://github.com/gabime/spdlog/archive/v1.13.0/spdlog-1.13.0.tar.gz
Summary  : Fast C++ logging library.
Group    : Development/Tools
License  : MIT
Requires: spdlog-lib = %{version}-%{release}
Requires: spdlog-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : fmt-dev
BuildRequires : glibc-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libsystemd)
BuildRequires : spdlog-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# spdlog
Very fast, header-only/compiled, C++ logging library. [![ci](https://github.com/gabime/spdlog/actions/workflows/ci.yml/badge.svg)](https://github.com/gabime/spdlog/actions/workflows/ci.yml)&nbsp; [![Build status](https://ci.appveyor.com/api/projects/status/d2jnxclg20vd0o50?svg=true&branch=v1.x)](https://ci.appveyor.com/project/gabime/spdlog) [![Release](https://img.shields.io/github/release/gabime/spdlog.svg)](https://github.com/gabime/spdlog/releases/latest)

%package dev
Summary: dev components for the spdlog package.
Group: Development
Requires: spdlog-lib = %{version}-%{release}
Provides: spdlog-devel = %{version}-%{release}
Requires: spdlog = %{version}-%{release}

%description dev
dev components for the spdlog package.


%package lib
Summary: lib components for the spdlog package.
Group: Libraries
Requires: spdlog-license = %{version}-%{release}

%description lib
lib components for the spdlog package.


%package license
Summary: license components for the spdlog package.
Group: Default

%description license
license components for the spdlog package.


%prep
%setup -q -n spdlog-1.13.0
cd %{_builddir}/spdlog-1.13.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1705168590
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :
cd ../clr-build-avx2;
make test || : || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1705168590
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/spdlog
cp %{_builddir}/spdlog-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/spdlog/bab970f85d9d9b485a36b93f8678fff4850d76fd || :
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/spdlog/async.h
/usr/include/spdlog/async_logger-inl.h
/usr/include/spdlog/async_logger.h
/usr/include/spdlog/cfg/argv.h
/usr/include/spdlog/cfg/env.h
/usr/include/spdlog/cfg/helpers-inl.h
/usr/include/spdlog/cfg/helpers.h
/usr/include/spdlog/common-inl.h
/usr/include/spdlog/common.h
/usr/include/spdlog/details/backtracer-inl.h
/usr/include/spdlog/details/backtracer.h
/usr/include/spdlog/details/circular_q.h
/usr/include/spdlog/details/console_globals.h
/usr/include/spdlog/details/file_helper-inl.h
/usr/include/spdlog/details/file_helper.h
/usr/include/spdlog/details/fmt_helper.h
/usr/include/spdlog/details/log_msg-inl.h
/usr/include/spdlog/details/log_msg.h
/usr/include/spdlog/details/log_msg_buffer-inl.h
/usr/include/spdlog/details/log_msg_buffer.h
/usr/include/spdlog/details/mpmc_blocking_q.h
/usr/include/spdlog/details/null_mutex.h
/usr/include/spdlog/details/os-inl.h
/usr/include/spdlog/details/os.h
/usr/include/spdlog/details/periodic_worker-inl.h
/usr/include/spdlog/details/periodic_worker.h
/usr/include/spdlog/details/registry-inl.h
/usr/include/spdlog/details/registry.h
/usr/include/spdlog/details/synchronous_factory.h
/usr/include/spdlog/details/tcp_client-windows.h
/usr/include/spdlog/details/tcp_client.h
/usr/include/spdlog/details/thread_pool-inl.h
/usr/include/spdlog/details/thread_pool.h
/usr/include/spdlog/details/udp_client-windows.h
/usr/include/spdlog/details/udp_client.h
/usr/include/spdlog/details/windows_include.h
/usr/include/spdlog/fmt/bin_to_hex.h
/usr/include/spdlog/fmt/bundled/args.h
/usr/include/spdlog/fmt/bundled/chrono.h
/usr/include/spdlog/fmt/bundled/color.h
/usr/include/spdlog/fmt/bundled/compile.h
/usr/include/spdlog/fmt/bundled/core.h
/usr/include/spdlog/fmt/bundled/fmt.license.rst
/usr/include/spdlog/fmt/bundled/format-inl.h
/usr/include/spdlog/fmt/bundled/format.h
/usr/include/spdlog/fmt/bundled/locale.h
/usr/include/spdlog/fmt/bundled/os.h
/usr/include/spdlog/fmt/bundled/ostream.h
/usr/include/spdlog/fmt/bundled/printf.h
/usr/include/spdlog/fmt/bundled/ranges.h
/usr/include/spdlog/fmt/bundled/std.h
/usr/include/spdlog/fmt/bundled/xchar.h
/usr/include/spdlog/fmt/chrono.h
/usr/include/spdlog/fmt/compile.h
/usr/include/spdlog/fmt/fmt.h
/usr/include/spdlog/fmt/ostr.h
/usr/include/spdlog/fmt/ranges.h
/usr/include/spdlog/fmt/std.h
/usr/include/spdlog/fmt/xchar.h
/usr/include/spdlog/formatter.h
/usr/include/spdlog/fwd.h
/usr/include/spdlog/logger-inl.h
/usr/include/spdlog/logger.h
/usr/include/spdlog/pattern_formatter-inl.h
/usr/include/spdlog/pattern_formatter.h
/usr/include/spdlog/sinks/android_sink.h
/usr/include/spdlog/sinks/ansicolor_sink-inl.h
/usr/include/spdlog/sinks/ansicolor_sink.h
/usr/include/spdlog/sinks/base_sink-inl.h
/usr/include/spdlog/sinks/base_sink.h
/usr/include/spdlog/sinks/basic_file_sink-inl.h
/usr/include/spdlog/sinks/basic_file_sink.h
/usr/include/spdlog/sinks/callback_sink.h
/usr/include/spdlog/sinks/daily_file_sink.h
/usr/include/spdlog/sinks/dist_sink.h
/usr/include/spdlog/sinks/dup_filter_sink.h
/usr/include/spdlog/sinks/hourly_file_sink.h
/usr/include/spdlog/sinks/kafka_sink.h
/usr/include/spdlog/sinks/mongo_sink.h
/usr/include/spdlog/sinks/msvc_sink.h
/usr/include/spdlog/sinks/null_sink.h
/usr/include/spdlog/sinks/ostream_sink.h
/usr/include/spdlog/sinks/qt_sinks.h
/usr/include/spdlog/sinks/ringbuffer_sink.h
/usr/include/spdlog/sinks/rotating_file_sink-inl.h
/usr/include/spdlog/sinks/rotating_file_sink.h
/usr/include/spdlog/sinks/sink-inl.h
/usr/include/spdlog/sinks/sink.h
/usr/include/spdlog/sinks/stdout_color_sinks-inl.h
/usr/include/spdlog/sinks/stdout_color_sinks.h
/usr/include/spdlog/sinks/stdout_sinks-inl.h
/usr/include/spdlog/sinks/stdout_sinks.h
/usr/include/spdlog/sinks/syslog_sink.h
/usr/include/spdlog/sinks/systemd_sink.h
/usr/include/spdlog/sinks/tcp_sink.h
/usr/include/spdlog/sinks/udp_sink.h
/usr/include/spdlog/sinks/win_eventlog_sink.h
/usr/include/spdlog/sinks/wincolor_sink-inl.h
/usr/include/spdlog/sinks/wincolor_sink.h
/usr/include/spdlog/spdlog-inl.h
/usr/include/spdlog/spdlog.h
/usr/include/spdlog/stopwatch.h
/usr/include/spdlog/tweakme.h
/usr/include/spdlog/version.h
/usr/lib64/cmake/spdlog/spdlogConfig.cmake
/usr/lib64/cmake/spdlog/spdlogConfigTargets-relwithdebinfo.cmake
/usr/lib64/cmake/spdlog/spdlogConfigTargets.cmake
/usr/lib64/cmake/spdlog/spdlogConfigVersion.cmake
/usr/lib64/libspdlog.so
/usr/lib64/pkgconfig/spdlog.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libspdlog.so.1.13.0
/usr/lib64/libspdlog.so.1.13
/usr/lib64/libspdlog.so.1.13.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/spdlog/bab970f85d9d9b485a36b93f8678fff4850d76fd
